# Full masks (e.g. to train bits only)
masks:
  kind: none

# The probability of applying the augmentation.
augs:
  identity:                 1
  jpeg:                     1
  resize:                   1
  crop:                     1
  rotate:                   1
  hflip:                    1
  perspective:              1
  gaussian_blur:            1
  median_filter:            1
  brightness:               1
  contrast:                 1
  saturation:               1
  hue:                      1
  h264:                     1
  h264rgb:                  1
  h265:                     1
  mbt2018_mean:             0
  mbt2018:                  0
  bmshj2018_hyperprior:     1
  bmshj2018_factorized:     0
  cheng2020_anchor:         0
  cheng2020_attn:           0
  stable_diffusion_vae:     1
  stable_diffusion_xl_vae:  0
  vqgan_1024:               0
  vqgan_16384:              1 

augs_params:
  # if there is no params, the augmentation will be applied with default params.
  resize:
    # edge size will be sampled from [min_size, max_size] * original edge size
    min_size: 0.3
    max_size: 2.0
  crop:
    min_size: 0.3
    max_size: 1.0
  rotate:
    min_angle: -20
    max_angle: 20
    do90: True
  perspective:
    min_distortion_scale: 0.1
    max_distortion_scale: 0.5
  jpeg:
    min_quality: 30
    max_quality: 80
  gaussian_blur:
    # sigma = 0.3 * ((kernel_size - 1) * 0.5 - 1) + 0.8
    min_kernel_size: 3
    max_kernel_size: 17
  median_filter:
    min_kernel_size: 3
    max_kernel_size: 3
  brightness:
    min_factor: 0.5
    max_factor: 2
  contrast:
    min_factor: 0.5
    max_factor: 2.0
  saturation:
    min_factor: 0.5
    max_factor: 2
  hue:
    min_factor: -0.1
    max_factor: 0.1
  h264:
    min_crf: 28
    max_crf: 36
  h264rgb:
    min_crf: 28
    max_crf: 36
  h265:
    min_crf: 28
    max_crf: 36
  mbt2018_mean:
    quality: 3
  mbt2018:
    quality: 3
  bmshj2018_hyperprior:
    quality: 3
  bmshj2018_factorized:
    quality: 3
  cheng2020_anchor:
    quality: 3
  cheng2020_attn:
    quality: 3