# Full masks (e.g. to train bits only)
masks:
  kind: none

# The probability of applying the augmentation.
augs:
  identity:       0.05
  jpeg:           0.5
  resize:         0.05
  crop:           0.05
  video_compression: 1
  rotate:         0.05
  hflip:          0.05
  perspective:    0.05
  gaussian_blur:  0.05
  median_filter:  0.05
  brightness:     0.05
  contrast:       0.05
  saturation:     0.05
  hue:            0.05

augs_params:
  resize:
    # edge size will be sampled from [min_size, max_size] * original edge size
    min_size: 0.7
    max_size: 1.5
  crop:
    min_size: 0.7
    max_size: 1.0
  rotate:
    min_angle: -10
    max_angle: 10
  perspective:
    min_distortion_scale: 0.1
    max_distortion_scale: 0.5
  jpeg:
    min_quality: 40
    max_quality: 80
  gaussian_blur:
    # sigma = 0.3 * ((kernel_size - 1) * 0.5 - 1) + 0.8
    min_kernel_size: 3
    max_kernel_size: 17
  median_filter:
    min_kernel_size: 3
    max_kernel_size: 7
  brightness:
    min_factor: 0.5
    max_factor: 2
  contrast:
    min_factor: 0.5
    max_factor: 2.0
  saturation:
    min_factor: 0.5
    max_factor: 2
  hue:
    min_factor: -0.1
    max_factor: 0.1
  video_compression:
    crf_values: [17, 28, 34, 40, 46]