# Mask kind. Choose between mixed, full, etc.
masks:
  kind: full
  invert_proba: 1.0

# # Full masks (e.g. to train bits only)
# masks:
#   kind: full
#   invert_proba: 1.0

# The probability of applying the augmentation.
# augs:
#   identity:       1
#   jpeg:           1
#   resize:         1
#   crop:           1
#   rotate:         1
#   hflip:          1
#   perspective:    1
#   gaussian_blur:  1
#   median_filter:  1
#   brightness:     1
#   contrast:       1
#   saturation:     1
#   hue:            1
#   # bmshj2018:      0

augs:
  identity:       1
  jpeg:           1
  resize:         
  crop:           0
  rotate:         0
  hflip:          0
  perspective:    0
  gaussian_blur:  0
  median_filter:  0
  brightness:     0
  contrast:       0
  saturation:     0
  hue:            0
  # bmshj2018:      0

augs_params:
  resize:
    min_size: 0.7
    max_size: 1.5
  crop:
    min_size: 0.7
    max_size: 1.0
  rotate:
    min_angle: -10
    max_angle: 10
  perspective:
    min_distortion_scale: 0.1
    max_distortion_scale: 0.5
  jpeg:
    min_quality: 40
    max_quality: 80
  gaussian_blur:
    # sigma = 0.3 * ((kernel_size - 1) * 0.5 - 1) + 0.8
    min_kernel_size: 3
    max_kernel_size: 17
  median_filter:
    min_kernel_size: 3
    max_kernel_size: 7
  brightness:
    min_factor: 0.5
    max_factor: 2
  contrast:
    min_factor: 0.5
    max_factor: 1.5
  saturation:
    min_factor: 0.5
    max_factor: 2
  hue:
    min_factor: -0.5
    max_factor: 0.5
  # bmshj2018:
  #   min_quality: 2
  #   max_quality: 4



# rot_params: Tuple[int, int] = (-10, 10),
# res_params: Tuple[float, float] = (0.7, 1.5),
# crop_params: Tuple[float, float] = (0.7, 1.0),
# persp_param: float = 0.1,