batched_augmenter: true

num_augs: 2

probabilities:
  geometric: 0.5
  valuemetric: 0.5
  compression: 0.3

geometric_params:
  params:
    resize:
      min_size: 0.7
      max_size: 1.5
      max_center_deviation: 0.5
    crop:
      min_size: 0.5
      max_size: 1.0
    rotate:
      min_angle: -10
      max_angle: 10
      prob_90deg: 0.5
    perspective:
      min_distortion_scale: -0.1
      max_distortion_scale: 0.5
    rotate_and_resize:
      min_angle: -10
      max_angle: 10
      prob_90deg: 0.5
      min_size: 1.0
      max_size: 1.5
      max_center_deviation: 0.5
  probs:
    resize: 1
    crop: 1
    rotate: 1
    perspective: 1
    rotate_and_resize: 1
    identity: 5
  fill: "random_color"
  random_hflip: true

valuemetric_params:
  params:
    gaussian_blur:
      min_kernel_size: 3
      max_kernel_size: 17
    brightness:
      min_factor: 0.5
      max_factor: 2
    contrast:
      min_factor: 0.5
      max_factor: 2
    saturation:
      min_factor: 0.5
      max_factor: 2
    hue:
      min_factor: -0.1
      max_factor: 0.1
  probs:
    gaussian_blur: 1
    brightness: 1
    contrast: 1
    saturation: 1
    hue: 1

compression_params:
  params:
    jpeg:
      min_quality: 40
      max_quality: 80
    h264:
      min_crf: 28
      max_crf: 36
    h264rgb:
      min_crf: 28
      max_crf: 36
    h265:
      min_crf: 28
      max_crf: 36
  probs:
    jpeg: 3
    h264: 1
    h264rgb: 1
    h265: 1
