model: dino2s_indices=2_5_8_11_upscale=1_14

# 1 hook

dino2s_indices=11_upscale=2_7:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [11]
  pixel_decoder:
    upscale_stages: [2, 7]  # 2*7 = x14 (patch size)
    embed_dim: 384  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=11_upscale=14_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [11]
  pixel_decoder:
    upscale_stages: [14, 1]  # 14*1 = x14 (patch size)
    embed_dim: 384  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=11_upscale=1_14:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [11]
  pixel_decoder:
    upscale_stages: [1, 14]  # 14*1 = x14 (patch size)
    embed_dim: 384  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=11_upscale=14_1_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [11]
  pixel_decoder:
    upscale_stages: [14, 1, 1]  # 14*1*1 = x14 (patch size)
    embed_dim: 384  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=11_upscale=1_1_14:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [11]
  pixel_decoder:
    upscale_stages: [1, 1, 14]  # 14*1*1 = x14 (patch size)
    embed_dim: 384  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

# 2 hooks

dino2s_indices=10_11_upscale=2_7:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [10, 11]
  pixel_decoder:
    upscale_stages: [2, 7]  # 2*7 = x14 (patch size)
    embed_dim: 768  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False
  
dino2s_indices=10_11_upscale=14_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [10, 11]
  pixel_decoder:
    upscale_stages: [14, 1]  # 14*1 = x14 (patch size)
    embed_dim: 768  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=10_11_upscale=14_1_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [10, 11]
  pixel_decoder:
    upscale_stages: [14, 1, 1]  # 14*1*1 = x14 (patch size)
    embed_dim: 768  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

# 4 hooks

dino2s_indices=2_5_8_11_upscale=2_7:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [2, 5, 8, 11]
  pixel_decoder:
    upscale_stages: [2, 7]  # 2*7 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=8_9_10_11_upscale=2_7:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [8, 9, 10, 11]
  pixel_decoder:
    upscale_stages: [2, 7]  # 2*7 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=2_5_8_11_upscale=14_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [2, 5, 8, 11]
  pixel_decoder:
    upscale_stages: [14, 1]  # 14*1 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=8_9_10_11_upscale=14_1:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [8, 9, 10, 11]
  pixel_decoder:
    upscale_stages: [14, 1]  # 14*1 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=2_5_8_11_upscale=1_14:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [2, 5, 8, 11]
  pixel_decoder:
    upscale_stages: [1, 14]  # 14*1 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2s_indices=8_9_10_11_upscale=1_14:
  encoder:
    name: 'dinov2_vits14'
    hook_indices: [8, 9, 10, 11]
  pixel_decoder:
    upscale_stages: [1, 14]  # 14*1 = x14 (patch size)
    embed_dim: 1536  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False

dino2b:
  encoder:
    name: 'dinov2_vitb14'
    hook_indices: ...
  pixel_decoder:
    upscale_stages: ...
    embed_dim: 192  # = len(encoder.hook_indices + encoder.out_chans
    nbits: 16
    sigmoid_output: False
