train_dir: /datasets01/COCO/060817/train2014/
train_annotation_file: /datasets01/COCO/060817/annotations/instances_train2014.json
val_dir: /datasets01/COCO/060817/val2014/
val_annotation_file: /datasets01/COCO/060817/annotations/instances_val2014.json