train_dir: /large_experiments/meres/sa-1b/anonymized_resized/train/
val_dir: /large_experiments/meres/sa-1b/anonymized_resized/valid/
train_annotation_file: /datasets01/segment_anything/annotations/release_040523/
val_annotation_file: /datasets01/segment_anything/annotations/release_040523/