train_dir: /large_experiments/meres/sa-1b/anonymized_resized/train_256p_resized/
val_dir: /large_experiments/meres/sa-1b/anonymized_resized/valid_256p_resized/
train_annotation_file: null
val_annotation_file: null