train_dir: /large_experiments/meres/sa-1b/anonymized_resized/train_0.3resized
val_dir: /large_experiments/meres/sa-1b/anonymized_resized/valid_0.3resized
train_annotation_file: null
val_annotation_file: null